// Code generated by "generate"; DO NOT EDIT.
package methods

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/isaacphi/mcp-language-server/internal/lsp"
	"github.com/isaacphi/mcp-language-server/internal/protocol"
)

// MethodCaller provides type-safe methods for LSP operationsWrapper
type MethodCaller struct {
	client *lsp.Client
}

// NewMethodCaller creates a new LSP method wrapper
func NewMethodCaller(client *lsp.Client) *MethodCaller {
	return &MethodCaller{client: client}
}

// Initialize sends a General request for initialize
func (w *MethodCaller) Initialize(params protocol.InitializeParams) (protocol.InitializeResult, error) {
	var result protocol.InitializeResult

	err := w.client.Call("initialize", params, &result)

	return result, err
}

// Initialized sends a General notification for initialized
func (w *MethodCaller) Initialized(params protocol.InitializedParams) error {

	return w.client.Notify("initialized", params)

}

// Shutdown sends a General request for shutdown
func (w *MethodCaller) Shutdown() error {

	return w.client.Call("shutdown", struct{}{}, nil)

}

// Exit sends a General notification for exit
func (w *MethodCaller) Exit() error {

	return w.client.Notify("exit", struct{}{})

}

// TextDocumentDidOpen sends a TextDocument notification for textDocument/didOpen
func (w *MethodCaller) TextDocumentDidOpen(params protocol.DidOpenTextDocumentParams) error {

	return w.client.Notify("textDocument/didOpen", params)

}

// TextDocumentDidChange sends a TextDocument notification for textDocument/didChange
func (w *MethodCaller) TextDocumentDidChange(params protocol.DidChangeTextDocumentParams) error {

	return w.client.Notify("textDocument/didChange", params)

}

// TextDocumentDidClose sends a TextDocument notification for textDocument/didClose
func (w *MethodCaller) TextDocumentDidClose(params protocol.DidCloseTextDocumentParams) error {

	return w.client.Notify("textDocument/didClose", params)

}

// TextDocumentWillSave sends a TextDocument notification for textDocument/willSave
func (w *MethodCaller) TextDocumentWillSave(params protocol.WillSaveTextDocumentParams) error {

	return w.client.Notify("textDocument/willSave", params)

}

// TextDocumentWillSaveWaitUntil sends a TextDocument request for textDocument/willSaveWaitUntil
func (w *MethodCaller) TextDocumentWillSaveWaitUntil(params protocol.WillSaveTextDocumentParams) ([]protocol.TextEdit, error) {
	var result []protocol.TextEdit

	err := w.client.Call("textDocument/willSaveWaitUntil", params, &result)

	return result, err
}

// TextDocumentDidSave sends a TextDocument notification for textDocument/didSave
func (w *MethodCaller) TextDocumentDidSave(params protocol.DidSaveTextDocumentParams) error {

	return w.client.Notify("textDocument/didSave", params)

}

// TextDocumentCompletion sends a TextDocument request for textDocument/completion
// Returns: protocol.CompletionList or []protocol.CompletionItem
func (w *MethodCaller) TextDocumentCompletion(params protocol.CompletionParams) (interface{}, error) {
	// Make single call and get raw response
	var rawResult json.RawMessage

	err := w.client.Call("textDocument/completion", params, &rawResult)

	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	// Try type CompletionList
	{
		var result0 protocol.CompletionList
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result0); err == nil {
			return result0, nil
		}
	}
	// Try type CompletionItem
	{
		var result1 []protocol.CompletionItem
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result1); err == nil {
			return result1, nil
		}
	}
	return nil, fmt.Errorf("response did not match any expected type")
}

// TextDocumentHover sends a TextDocument request for textDocument/hover
func (w *MethodCaller) TextDocumentHover(params protocol.HoverParams) (protocol.Hover, error) {
	var result protocol.Hover

	err := w.client.Call("textDocument/hover", params, &result)

	return result, err
}

// TextDocumentSignatureHelp sends a TextDocument request for textDocument/signatureHelp
func (w *MethodCaller) TextDocumentSignatureHelp(params protocol.SignatureHelpParams) (protocol.SignatureHelp, error) {
	var result protocol.SignatureHelp

	err := w.client.Call("textDocument/signatureHelp", params, &result)

	return result, err
}

// TextDocumentDefinition sends a TextDocument request for textDocument/definition
// Returns: protocol.Location or []protocol.Location or []protocol.DefinitionLink
func (w *MethodCaller) TextDocumentDefinition(params protocol.DefinitionParams) (interface{}, error) {
	// Make single call and get raw response
	var rawResult json.RawMessage

	err := w.client.Call("textDocument/definition", params, &rawResult)

	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	// Try type Location
	{
		var result0 protocol.Location
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result0); err == nil {
			return result0, nil
		}
	}
	// Try type Location
	{
		var result1 []protocol.Location
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result1); err == nil {
			return result1, nil
		}
	}
	// Try type DefinitionLink
	{
		var result2 []protocol.DefinitionLink
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result2); err == nil {
			return result2, nil
		}
	}
	return nil, fmt.Errorf("response did not match any expected type")
}

// TextDocumentDeclaration sends a TextDocument request for textDocument/declaration
// Returns: protocol.Location or []protocol.Location or []protocol.DeclarationLink
func (w *MethodCaller) TextDocumentDeclaration(params protocol.DeclarationParams) (interface{}, error) {
	// Make single call and get raw response
	var rawResult json.RawMessage

	err := w.client.Call("textDocument/declaration", params, &rawResult)

	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	// Try type Location
	{
		var result0 protocol.Location
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result0); err == nil {
			return result0, nil
		}
	}
	// Try type Location
	{
		var result1 []protocol.Location
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result1); err == nil {
			return result1, nil
		}
	}
	// Try type DeclarationLink
	{
		var result2 []protocol.DeclarationLink
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result2); err == nil {
			return result2, nil
		}
	}
	return nil, fmt.Errorf("response did not match any expected type")
}

// TextDocumentReferences sends a TextDocument request for textDocument/references
func (w *MethodCaller) TextDocumentReferences(params protocol.ReferenceParams) ([]protocol.Location, error) {
	var result []protocol.Location

	err := w.client.Call("textDocument/references", params, &result)

	return result, err
}

// TextDocumentDocumentHighlight sends a TextDocument request for textDocument/documentHighlight
func (w *MethodCaller) TextDocumentDocumentHighlight(params protocol.DocumentHighlightParams) ([]protocol.DocumentHighlight, error) {
	var result []protocol.DocumentHighlight

	err := w.client.Call("textDocument/documentHighlight", params, &result)

	return result, err
}

// TextDocumentDocumentSymbol sends a TextDocument request for textDocument/documentSymbol
// Returns: []protocol.DocumentSymbol or []protocol.SymbolInformation
func (w *MethodCaller) TextDocumentDocumentSymbol(params protocol.DocumentSymbolParams) (interface{}, error) {
	// Make single call and get raw response
	var rawResult json.RawMessage

	err := w.client.Call("textDocument/documentSymbol", params, &rawResult)

	if err != nil {
		return nil, fmt.Errorf("request failed: %w", err)
	}

	// Try type DocumentSymbol
	{
		var result0 []protocol.DocumentSymbol
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result0); err == nil {
			return result0, nil
		}
	}
	// Try type SymbolInformation
	{
		var result1 []protocol.SymbolInformation
		decoder := json.NewDecoder(bytes.NewReader(rawResult))
		decoder.UseNumber()
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&result1); err == nil {
			return convertSymbolInformationSliceToDocumentSymbolSlice(result1), nil
		}
	}
	return nil, fmt.Errorf("response did not match any expected type")
}

// TextDocumentFormatting sends a TextDocument request for textDocument/formatting
func (w *MethodCaller) TextDocumentFormatting(params protocol.DocumentFormattingParams) ([]protocol.TextEdit, error) {
	var result []protocol.TextEdit

	err := w.client.Call("textDocument/formatting", params, &result)

	return result, err
}

// TextDocumentRangeFormatting sends a TextDocument request for textDocument/rangeFormatting
func (w *MethodCaller) TextDocumentRangeFormatting(params protocol.DocumentRangeFormattingParams) ([]protocol.TextEdit, error) {
	var result []protocol.TextEdit

	err := w.client.Call("textDocument/rangeFormatting", params, &result)

	return result, err
}
