// Code generated by "generate"; DO NOT EDIT.
package methods

// Registry maintains the mapping of LSP method names to their handlers
type Registry struct {
	methods map[string]bool
}

// NewRegistry creates a new method registry
func NewRegistry() *Registry {
	return &Registry{
		methods: make(map[string]bool),
	}
}

// RegisterMethod marks a method as available
func (r *Registry) RegisterMethod(name string) {
	r.methods[name] = true
}

// HasMethod checks if a method is available
func (r *Registry) HasMethod(name string) bool {
	return r.methods[name]
}

// Known LSP methods
const (
	TextDocumentDidOpenMethod        = "textDocument/didOpen"
	TextDocumentDidChangeMethod      = "textDocument/didChange"
	TextDocumentDidCloseMethod       = "textDocument/didClose"
	TextDocumentDidSaveMethod        = "textDocument/didSave"
	TextDocumentDocumentSymbolMethod = "textDocument/documentSymbol"
	WorkspaceSymbolMethod            = "workspace/symbol"
	TextDocumentDefinitionMethod     = "textDocument/definition"
	TextDocumentFormattingMethod     = "textDocument/formatting"
	TextDocumentHoverMethod          = "textDocument/hover"
	TextDocumentReferencesMethod     = "textDocument/references"
)
